[package]
name = "scanner-rust"
version = "3.0.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.89"
repository = "https://github.com/magiclen/scanner-rust"
homepage = "https://magiclen.org/scanner-rust"
keywords = ["scanner", "java", "read", "stdin", "stream"]
categories = ["parser-implementations"]
description = "Simple text scanners which can parse primitive types and strings using UTF-8 or ASCII."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
utf8-width = "0.1"

educe = { version = "0.7", default-features = false, features = ["Debug"] }